version: '3'
services:
  mongo:
    image: mongo:3.4
    restart: always
    network_mode: host
    ports:
      - 27017:27017
    command: --config /etc/mongo/mongod.conf

  creditscore:
    build: .
    network_mode: host
    ports:
      - 8082:8082
    depends_on:
      - mongo
