server:
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    platform: org.hibernate.dialect.PostgreSQL94Dialect
    url: jdbc:postgresql://localhost:5432/loanapplication?createDatabaseIfNotExist=true
    username: postgres
    password: postgres
client:
  credit-score-service:
    url: http://localhost:8082
  notification:
    url: http://localhost:8081
