server:
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    platform: platform
    url: jdbc:h2:mem:loanapplication
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
client:
  credit-score-service:
    url: http://localhost:8082
  notification:
    url: http://localhost:8081
